### DISCUSSION TITLE
toml inspirations

### DISCUSSION THREAD

**Discussion by amitu** [fastn-stack/fastn#884] [Ideas & RFCs]
@Arpita-Jaiswal been going through [TOML spec](https://toml.io/en/v1.0.0), I think they have some ideas we should pick.

# Dotted Keys

```toml
name = "Orange"
physical.color = "orange"
physical.shape = "round"
site."google.com" = true
```

is equivalent to 

```json
{
  "name": "Orange",
  "physical": {
    "color": "orange",
    "shape": "round"
  },
  "site": {
    "google.com": true
  }
}
```

We can use these for complex record and component arguments.

# Numbers With Separators

```toml
x = 1_000
```

Makes larger numbers easier to read.

# Inline "table"

```toml
point = { x = 1, y = 2 }
```

Along with the multiline version:

```toml
point = { 
  x = 1, 
  y = 2 
}
```
