### DISCUSSION TITLE
creating shadow effetcs for text

### DISCUSSION THREAD

**Discussion by AthulA10** [fastn-stack/fastn#936] [Ideas & RFCs]
```css
p {
    text-shadow: 3px -3px 0px #000000, -3px -3px 0px #000000, 3px 3px 0px #000000, 0px 4px 0px #000000, 0px -4px 0px #000000, 4px 0px 0px #000000, -8px 7px 0px #000000;
}
```

How can we achieve a text shadow effect like this?
