### ISSUE TITLE
Remove default margin added to `p` tag

### ISSUE THREAD

**Issue by gsalunke** [fastn-stack/fastn#196]
When we build package via using `fpm build` 
the generated HTML file contains below css:
```css
.ft_md ul, .ft_md ol, .ft_md p {
    margin: 10px 0;
}
```
Remove `margin: 10px 0;` and change it with `margin: 0;`
