### ISSUE TITLE
Blockquote CSS missing left border

### ISSUE THREAD

**Issue by gsalunke** [fastn-stack/fastn#972]
Currently below is the CSS applied when we use markdown `blockquote` (`> some info`).

```css
.ft_md blockquote {
    padding: 0.25rem 1rem;
    margin: 1rem 0;
    border-radius: 3px;
}
```
Blockquote should be visible clearly, so, can we update above CSS with:

```css
.ft_md blockquote {
    padding: 0.25rem 1rem;
    margin: 1rem 0;
    border-left: 4px solid #30363d;
}
```
